<Project>
    <PropertyGroup>
        <LangVersion>latestmajor</LangVersion>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <ImplicitUsings>true</ImplicitUsings>
        <RepositoryUrl>https://github.com/meshmakers/mm-common.git</RepositoryUrl>
        <PackageIcon>meshmakers64.png</PackageIcon>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageProjectUrl>https://www.meshmakers.io</PackageProjectUrl>
        <PackageTags>Octo data mesh iot</PackageTags>
        <PackageVersion Condition="'$(Configuration)'=='DebugL'">999.0.0</PackageVersion>
        <Version Condition="'$(Configuration)'=='DebugL'">999.0.0</Version>
        <TargetFrameworks>net10.0</TargetFrameworks>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'DebugL' ">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <None Include="$([System.IO.Path]::Combine('$(MSBuildThisFileDirectory)','README.md'))" Pack="True" PackagePath="" Visible="false" />
    </ItemGroup>
</Project>
