<Project>
    <PropertyGroup>
        <Authors>meshmakers GmbH and Contributors</Authors>
        <Company>meshmakers GmbH and Contributors</Company>
        <Copyright>(c) 2022-2024 meshmakers GmbH</Copyright>
        <LangVersion>latestmajor</LangVersion>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <ImplicitUsings>true</ImplicitUsings>
        <RepositoryUrl>https://github.com/meshmakers/common.git</RepositoryUrl>
        <PackageIcon>meshmakers64.png</PackageIcon>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageProjectUrl>https://www.meshmakers.io</PackageProjectUrl>
        <PackageTags>Octo data mesh iot</PackageTags>
    </PropertyGroup>
</Project>
