# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)

trigger:
  batch: true
  branches:
    include:
      - dev/*
      - main
  tags:
    exclude:
      - '*'

pool:
  name: Gerald-Local-Linux

variables:
  - group: ApiKeys
  - group: OctoDefault
  - name: solution
    value: '**/*.sln'
  - name: isRelease
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}
  - name: buildConfiguration
    value: 'Release'
  - name: buildPlatform
    value: 'Any CPU'
  - name: isRelease
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}
  - name: isMain
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}

steps:
- template: set-version.yml
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(solution)'
- task: DotNetCoreCLI@2
  displayName: Tests
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(solution)'
- task: CopyFiles@2
  displayName: 'Copy Files from **/*.nupkg to $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    Contents: |
      **/*.nupkg
    TargetFolder: $(build.artifactstagingdirectory)/nuget
    flattenFolders: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: local'
  inputs:
    ArtifactName: local
- template: push-nuget-package.yml
