<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>Meshmakers.Common.SharedTests</AssemblyName>
        <Authors>meshmakers GmbH</Authors>
        <Company>Meshmakers.Common.SharedTests</Company>
        <IsPackable>false</IsPackable>
        <LangVersion>latestmajor</LangVersion>
        <Nullable>enable</Nullable>
        <PackageIcon>meshmakers64.png</PackageIcon>
        <PackageId>Meshmakers.Common.SharedTests</PackageId>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageProjectUrl>https://www.meshmakers.io</PackageProjectUrl>
        <Product>Meshmakers.Common.SharedTests</Product>
        <RepositoryUrl>https://github.com/meshmakers/common/</RepositoryUrl>
        <RootNamespace>Meshmakers.Common.SharedTests</RootNamespace>
        <SignAssembly>false</SignAssembly>
        <TargetFramework>net6.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
        <PackageReference Include="xunit" Version="2.4.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="3.1.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Moq" Version="4.17.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Shared\Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\assets\meshmakers64.png">
            <Pack>True</Pack>
            <PackagePath />
            <Link>meshmakers64.png</Link>
        </None>
    </ItemGroup>

</Project>