<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>Meshmakers.Common.Shared</AssemblyName>
        <Authors>meshmakers GmbH</Authors>
        <Company>meshmakers GmbH</Company>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <LangVersion>latestmajor</LangVersion>
        <Nullable>enable</Nullable>
        <PackageIcon>meshmakers64.png</PackageIcon>
        <PackageId>Meshmakers.Common.Shared</PackageId>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageProjectUrl>https://www.meshmakers.io</PackageProjectUrl>
        <RepositoryUrl>https://github.com/meshmakers/common/</RepositoryUrl>
        <RootNamespace>Meshmakers.Common.Shared</RootNamespace>
        <SignAssembly>false</SignAssembly>
        <TargetFramework>net6.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2022.1.0" />
        <PackageReference Include="System.Composition.TypedParts" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath />
            <Link>LICENSE</Link>
        </None>
        <None Include="..\..\assets\meshmakers64.png">
            <Pack>True</Pack>
            <PackagePath />
            <Link>meshmakers64.png</Link>
        </None>
    </ItemGroup>

</Project>