<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>Meshmakers.Common.Shared</AssemblyName>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>Meshmakers.Common.Shared</PackageId>
        <RootNamespace>Meshmakers.Common.Shared</RootNamespace>
        <SignAssembly>false</SignAssembly>
        <TargetFrameworks>net7.0;net8.0;netstandard2.0</TargetFrameworks>
        <TargetFramework />
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2023.3.0" />
        <PackageReference Include="System.Composition.TypedParts" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath />
            <Link>LICENSE</Link>
        </None>
        <None Include="..\..\assets\meshmakers64.png">
            <Pack>True</Pack>
            <PackagePath />
            <Link>meshmakers64.png</Link>
        </None>
    </ItemGroup>

</Project>
