<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>Meshmakers.Common.CommandLineParser</AssemblyName>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>Meshmakers.Common.CommandLineParser</PackageId>
        <RootNamespace>Meshmakers.Common.CommandLineParser</RootNamespace>
        <SignAssembly>false</SignAssembly>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Meshmakers.Common.CommandLineParserTests" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath />
            <Link>LICENSE</Link>
        </None>
        <None Include="..\..\assets\meshmakers64.png">
            <Pack>True</Pack>
            <PackagePath />
            <Link>meshmakers64.png</Link>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.0" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="7.0.0" />
        <PackageReference Include="System.Composition.AttributedModel" Version="7.0.0" />
        <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
        <PackageReference Include="System.Security.AccessControl" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

</Project>