<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <SignAssembly>false</SignAssembly>
        <RootNamespace>Meshmakers.Common.CommandLineParser</RootNamespace>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageProjectUrl>https://www.meshmakers.io</PackageProjectUrl>
        <PackageIcon>meshmakers64.png</PackageIcon>
        <PackageId>Meshmakers.Common.CommandLineParser</PackageId>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <LangVersion>latestmajor</LangVersion>
        <Nullable>enable</Nullable>
        <RepositoryUrl>https://github.com/meshmakers/common/</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="CommandLineParserTests"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath/>
            <Link>LICENSE</Link>
        </None>
        <None Include="..\..\assets\meshmakers64.png">
            <Pack>True</Pack>
            <PackagePath/>
            <Link>meshmakers64.png</Link>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Composition.AttributedModel" Version="6.0.0"/>
        <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0"/>
        <PackageReference Include="System.Security.AccessControl" Version="6.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shared\Shared.csproj"/>
    </ItemGroup>

</Project>