<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>Meshmakers.Common.Metrics</AssemblyName>
        <Authors>meshmakers GmbH</Authors>
        <Company>meshmakers GmbH</Company>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latestmajor</LangVersion>
        <Nullable>enable</Nullable>
        <PackageIcon>meshmakers64.png</PackageIcon>
        <PackageId>Meshmakers.Common.Metrics</PackageId>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageProjectUrl>https://www.meshmakers.io</PackageProjectUrl>
        <RepositoryUrl>https://github.com/meshmakers/common/</RepositoryUrl>
        <RootNamespace>Meshmakers.Common.Metrics</RootNamespace>
        <TargetFramework>net6.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Meshmakers.Common.MetricsTests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="prometheus-net" Version="7.0.0-pre-000305-75cc817" />
        <PackageReference Include="prometheus-net.AspNetCore" Version="7.0.0-pre-000305-75cc817" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath />
            <Link>LICENSE</Link>
        </None>
        <None Include="..\..\assets\meshmakers64.png">
            <Pack>True</Pack>
            <PackagePath />
            <Link>meshmakers64.png</Link>
        </None>
    </ItemGroup>

</Project>