<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>Meshmakers.Common.Metrics</AssemblyName>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Meshmakers.Common.Metrics</PackageId>
        <RootNamespace>Meshmakers.Common.Metrics</RootNamespace>
        <TargetFrameworks>net7.0;net8.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Meshmakers.Common.MetricsTests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="prometheus-net" Version="8.2.0" />
        <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath />
            <Link>LICENSE</Link>
        </None>
        <None Include="..\..\assets\meshmakers64.png">
            <Pack>True</Pack>
            <PackagePath />
            <Link>meshmakers64.png</Link>
        </None>
    </ItemGroup>

</Project>
